name: Deploy React Portfolio

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Set homepage and repository fields
        run: |
          # Set the homepage to your custom domain.
          npx json -I -f package.json -e 'this.homepage="https://amansingh.dev"'
          # Update the repository field with token-based URL for authentication.
          npx json -I -f package.json -e "this.repository={ \"type\": \"git\", \"url\": \"https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git\" }"
          
      - name: Build the app
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
